<?php
add_action( 'init', 'slidstvo_cpt_init' );
function slidstvo_cpt_init() {
	register_post_type(
		'news',
		array(
			'labels'              =>
				array(
					'name'               => 'Новини',
					'singular_name'      => 'Новина',
					'add_new'            => 'Додати новину',
					'add_new_item'       => 'Додати новину',
					'edit_item'          => 'Редагувати новину',
					'new_item'           => 'Додати новину',
					'view_item'          => 'Переглянути Новина',
					'search_items'       => 'Шукати Новини',
					'not_found'          => 'Новини не знайдено',
					'not_found_in_trash' => 'Новини немає',
					'all_items'          => 'Всі новини',
				),
			'public'              => true,
			'menu_position'       => 20,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'comments',
					3                 => 'author',
					4                 => 'excerpt',
					5                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'news',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-list-view',
		)
	);

	register_post_type(
		'video',
		array(
			'labels'              =>
				array(
					'name'               => 'Фільми',
					'singular_name'      => 'Фільм',
					'add_new'            => 'Додати фільм',
					'add_new_item'       => 'Додати фільм',
					'edit_item'          => 'Редагувати Фільм',
					'new_item'           => 'Додати фільм',
					'view_item'          => 'Переглянути фільм',
					'search_items'       => 'Шукати Фільми',
					'not_found'          => 'Фільми не знайдено',
					'not_found_in_trash' => 'Фільми немає',
					'all_items'          => 'Всі фільми',
				),
			'public'              => true,
			'menu_position'       => 20,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'comments',
					3                 => 'author',
					4                 => 'excerpt',
					5                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'video',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-controls-play',
		)
	);

	register_post_type(
		'special-projects',
		array(
			'labels'              =>
				array(
					'name'               => 'Спецпроєкти',
					'singular_name'      => 'Спецпроєкт',
					'add_new'            => 'Додати спецпроєкт',
					'add_new_item'       => 'Додати спецпроєкт',
					'edit_item'          => 'Редагувати спецпроєкт',
					'new_item'           => 'Додати спецпроєкт',
					'view_item'          => 'Перглянути спецпроєкт',
					'search_items'       => 'Шукати Спецпроєкти',
					'not_found'          => 'Спецпроєкти не знайдено',
					'not_found_in_trash' => 'Спецпроєкти немає',
					'all_items'          => 'Всі спецпроєкти',
				),
			'public'              => true,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'comments',
					3                 => 'author',
					4                 => 'excerpt',
					5                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'special-projects',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-album',
		)
	);

	register_post_type(
		'blogs',
		array(
			'labels'              =>
				array(
					'name'               => 'Блоги',
					'singular_name'      => 'Блог',
					'add_new'            => 'Додати блог',
					'add_new_item'       => 'Додати блог',
					'edit_item'          => 'Редагувати блог',
					'new_item'           => 'Додати блог',
					'view_item'          => 'Переглянути блог',
					'search_items'       => 'Шукати блог',
					'not_found'          => 'Блоги не знайдено',
					'not_found_in_trash' => 'Блоги немає',
					'all_items'          => 'Всі блоги',
				),
			'public'              => true,
			'menu_position'       => 20,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'excerpt',
					3                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'blogs',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-welcome-write-blog',
		)
	);

	register_post_type(
		'articles',
		array(
			'labels'              =>
				array(
					'name'               => 'Статті',
					'singular_name'      => 'Стаття',
					'add_new'            => 'Додати статтю',
					'add_new_item'       => 'Додати статтю',
					'edit_item'          => 'Редагувати статтю',
					'new_item'           => 'Додати статтю',
					'view_item'          => 'Переглянути статтю',
					'search_items'       => 'Шукати Статті',
					'not_found'          => 'Статті не знайдено',
					'not_found_in_trash' => 'Статті немає',
					'all_items'          => 'Всі статті',
				),
			'public'              => true,
			'menu_position'       => 20,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'comments',
					3                 => 'author',
					4                 => 'excerpt',
					5                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'articles',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-archive',
		)
	);

	register_post_type(
		'banners',
		array(
			'labels'              =>
				array(
					'name'               => 'Банери',
					'singular_name'      => 'Банер',
					'add_new'            => 'Додати банер',
					'add_new_item'       => 'Додати банер',
					'edit_item'          => 'Редагувати банер',
					'new_item'           => 'Додати банер',
					'view_item'          => 'Переглянути банер',
					'search_items'       => 'Шукати банер',
					'not_found'          => 'Банери не знайдено',
					'not_found_in_trash' => 'Банери немає',
					'all_items'          => 'Всі банери',
				),
			'public'              => true,
			'menu_position'       => 25,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'banners',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-align-center',
		)
	);

	register_post_type(
		'animation',
		array(
			'labels'              =>
				array(
					'name'               => 'Анімація',
					'singular_name'      => 'Анімація.',
					'add_new'            => 'Додати анімацію',
					'add_new_item'       => 'Додати анімацію',
					'edit_item'          => 'Редагувати анімацію',
					'new_item'           => 'Додати анімацію',
					'view_item'          => 'Переглянути анімацію',
					'search_items'       => 'Шукати Анімація',
					'not_found'          => 'Анімація не знайдено',
					'not_found_in_trash' => 'Анімація немає',
					'all_items'          => 'Всі анімації',
				),
			'public'              => true,
			'menu_position'       => 20,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'animation',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-universal-access-alt',
		)
	);

	register_post_type(
		'events',
		array(
			'labels'              =>
				array(
					'name'               => 'Події',
					'singular_name'      => 'Подія',
					'add_new'            => 'Додати подію',
					'add_new_item'       => 'Додати подію',
					'edit_item'          => 'Редагувати подію',
					'new_item'           => 'Додати подію',
					'view_item'          => 'Переглянути подію',
					'search_items'       => 'Шукати Події',
					'not_found'          => 'Події не знайдено',
					'not_found_in_trash' => 'Події немає',
					'all_items'          => 'Всі події',
				),
			'public'              => true,
			'menu_position'       => 25,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'excerpt',
					3                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'events',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-calendar',
		)
	);

	register_post_type(
		'partners',
		array(
			'labels'              =>
				array(
					'name'               => 'Партнери',
					'singular_name'      => 'partner',
					'add_new'            => 'Додати парнтера',
					'add_new_item'       => 'Додати парнтера',
					'edit_item'          => 'Редагувати партнера',
					'new_item'           => 'Додати парнтера',
					'view_item'          => 'Переглянути партнера',
					'search_items'       => 'Шукати Партнери',
					'not_found'          => 'Партнери не знайдено',
					'not_found_in_trash' => 'Партнери немає',
					'all_items'          => 'Всі партнери',
				),
			'public'              => true,
			'menu_position'       => 25,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'excerpt',
					3                 => 'thumbnail',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'partners',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-groups',
		)
	);

	register_post_type(
		'success-stories',
		array(
			'labels'              =>
				array(
					'name'               => 'Історії успіху',
					'singular_name'      => 'Історія успіху',
					'add_new'            => 'Додати  історію успіху',
					'add_new_item'       => 'Додати історію успіху Історія успіху',
					'edit_item'          => 'Редагувати  історію успіху Історія успіху',
					'new_item'           => 'New Історія успіху',
					'view_item'          => 'Переглянути  Історія успіху',
					'search_items'       => 'Search Історії успіху',
					'not_found'          => 'No Історії успіху found',
					'not_found_in_trash' => 'No Історії успіху found in Trash',
					'all_items'          => 'Історії успіху',
				),
			'public'              => true,
			'menu_position'       => 25,
			'supports'            =>
				array(
					0                 => 'title',
					1                 => 'editor',
					2                 => 'excerpt',
					3                 => 'thumbnail',
					4                 => 'custom-fields',
					5                 => 'post-formats',
					'editor'          => false,
					'author'          => false,
					'thumbnail'       => false,
					'excerpt'         => false,
					'trackbacks'      => false,
					'custom-fields'   => false,
					'comments'        => false,
					'revisions'       => false,
					'page-attributes' => false,
					'post-formats'    => false,
				),
			'has_archive'         => true,
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'rest_base'           => 'success-stories',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-awards',
		)
	);

	register_post_type(
		'warnews',
		array(
			'labels'              => array(
				'name'               => 'Вiйна',
				'singular_name'      => 'Стаття',
				'add_new'            => 'Додати статтю',
				'add_new_item'       => 'Додати статтю',
				'edit_item'          => 'Редагувати статтю',
				'new_item'           => 'Додати статтю',
				'view_item'          => 'Переглянути статтю',
				'search_items'       => 'Шукати Вiйна',
				'not_found'          => 'Вiйна не знайдено',
				'not_found_in_trash' => 'Вiйна немає',
				'parent_item_colon'  => 'Parent text',
				'all_items'          => 'Всі статтi',
				'enter_title_here'   => 'Enter title here',
			),
			'slug'                => 'warnews',
			'description'         => '',
			'public'              => true,
			'menu_position'       => 25,
			'supports'            => array(
				0                 => 'title',
				1                 => 'editor',
				2                 => 'comments',
				3                 => 'author',
				4                 => 'excerpt',
				5                 => 'thumbnail',
				'editor'          => false,
				'author'          => false,
				'thumbnail'       => false,
				'excerpt'         => false,
				'trackbacks'      => false,
				'custom-fields'   => false,
				'comments'        => false,
				'revisions'       => false,
				'page-attributes' => false,
				'post-formats'    => false,
			),
			'rewrite'             => array(
				'enabled'    => '1',
				'with_front' => true,
				'feeds'      => true,
				'pages'      => true,
			),
			'has_archive'         => true,
			'has_archive_slug'    => '',
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'permalink_epmask'    => 1,
			'rest_base'           => 'warnews',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-calendar',
		)
	);

	register_post_type(
		'english-stories',
		array(
			'labels'              => array(
				'name'               => 'English stories',
				'singular_name'      => 'English story',
				'add_new'            => 'Додати статтю',
				'add_new_item'       => 'Додати статтю',
				'edit_item'          => 'Редагувати статтю',
				'new_item'           => 'Додати статтю',
				'view_item'          => 'Переглянути статтю',
				'search_items'       => 'Шукати English stories',
				'not_found'          => 'English stories не знайдено',
				'not_found_in_trash' => 'English stories немає',
				'parent_item_colon'  => 'Parent text',
				'all_items'          => 'Всі статті',
				'enter_title_here'   => 'Enter title here',
			),
			'slug'                => 'english-stories',
			'description'         => '',
			'public'              => true,
			'menu_position'       => 20,
			'supports'            => array(
				0                 => 'title',
				1                 => 'editor',
				2                 => 'comments',
				3                 => 'author',
				4                 => 'excerpt',
				5                 => 'thumbnail',
				'editor'          => false,
				'author'          => false,
				'thumbnail'       => false,
				'excerpt'         => false,
				'trackbacks'      => false,
				'custom-fields'   => false,
				'comments'        => false,
				'revisions'       => false,
				'page-attributes' => false,
				'post-formats'    => false,
			),
			'rewrite'             => array(
				'enabled'    => '1',
				'with_front' => true,
				'feeds'      => true,
				'pages'      => true,
			),
			'has_archive'         => true,
			'has_archive_slug'    => '',
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'permalink_epmask'    => 1,
			'rest_base'           => 'english-stories',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-archive',
		)
	);

	register_post_type(
		'shelters',
		array(
			'labels'              => array(
				'name'               => 'Укриття',
				'singular_name'      => 'Укриття',
				'add_new'            => 'Додати укриття',
				'add_new_item'       => 'Додати укриття',
				'edit_item'          => 'Редагувати укриття',
				'new_item'           => 'Додати укриття',
				'view_item'          => 'Переглянути укриття',
				'search_items'       => 'Шукати укриття',
				'not_found'          => 'Укриття не знайдено',
				'not_found_in_trash' => 'Укриття немає',
				'parent_item_colon'  => 'Parent text',
				'all_items'          => 'Всі укриття',
				'enter_title_here'   => 'Enter title here',
			),
			'slug'                => 'shelters',
			'description'         => '',
			'public'              => true,
			'menu_position'       => 25,
			'supports'            => array(
				0                 => 'title',
				1                 => 'editor',
				2                 => 'comments',
				3                 => 'author',
				4                 => 'excerpt',
				5                 => 'thumbnail',
				'editor'          => false,
				'author'          => false,
				'thumbnail'       => false,
				'excerpt'         => false,
				'trackbacks'      => false,
				'custom-fields'   => false,
				'comments'        => false,
				'revisions'       => false,
				'page-attributes' => false,
				'post-formats'    => false,
			),
			'rewrite'             => array(
				'enabled'    => '1',
				'with_front' => true,
				'feeds'      => true,
				'pages'      => true,
			),
			'has_archive'         => true,
			'has_archive_slug'    => '',
			'show_in_menu'        => true,
			'show_in_menu_page'   => '',
			'show_ui'             => true,
			'publicly_queryable'  => true,
			'can_export'          => true,
			'show_in_nav_menus'   => true,
			'query_var_enabled'   => '1',
			'query_var'           => true,
			'permalink_epmask'    => 1,
			'rest_base'           => 'shelters',
			'exclude_from_search' => false,
			'hierarchical'        => false,
			'show_in_rest'        => false,
			'menu_icon'           => 'dashicons-calendar',
		)
	);

}



